

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    org.keycloak: DEBUG

security:
  basic:
    enabled: false

keycloak:
  realm: isp
  auth-server-url: http://localhost:8001/auth
  ssl-required: external
  resource: portal
  credentials.secret: 387ef481-b296-4f56-8792-4cee4151d523
  use-resource-role-mappings: true
