

server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG

security:
  basic:
    enabled: false

keycloak:
  realm: demorealm
  auth-server-url: http://localhost:8001/auth
  ssl-required: external
  resource: demoapp
  credentials.secret: 11111111-1111-1111-1111-111111111111
  use-resource-role-mappings: true
